name: Ping event

on:
  push:
    branches:
    - 'release/2.x'
    - 'release/3.x'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Hello World
      run: |
        echo "Hello World at ${{ github.ref_name }} from release branch 3.x"
